src/claires/api/urls.py
from django.conf.urls import patterns, url, include
from claires.views import ClairesView
from .views import *
from rest_framework import routers
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework_cache.registry import cache_registry
cache_registry.autodiscover()

router = routers.DefaultRouter()
router.register(r'jobsapply', VacanApplyViewSet)
router.register(r'groups', GroupViewSet)
router.register(r'category', CategoryViewSet)
router.register(r'stores', StoresViewSet)
router.register(r'products', ProductViewSet)
router.register(r'products_search', ProductSearchViewSet)
router.register(r'product_stores', ProductStoreViewSet)
router.register(r'props', PropViewSet)
router.register(r'prop_vars', PropVarViewSet)



urlpatterns = [
    url(r'^', include(router.urls, namespace='api'))
]

#urlpatterns = format_suffix_patterns(urlpatterns)

src/claires/pages/urls.py
from django.conf.urls import patterns, url, include
from .views import PageView

urlpatterns = patterns('',
    url(r'(?P<parent>[\w\d\-]+)/(?P<page_slug>[\w\d\-]+)', PageView.as_view()),
    url(r'(?P<parent>[\w\d\-]+)/$', PageView.as_view()),
)

src/claires/search/urls.py
from django.conf.urls import patterns, url, include
from .views import SearchView

urlpatterns = patterns('',
    url(r'$', SearchView.as_view()),
)

src/claires/user/urls.py
from django.conf.urls import patterns, url, include
from .views import *

urlpatterns = patterns('',
    url(r'register$', RegisterView.as_view(), {"gift":None} ),
    url(r'register/phone_check/$', phone_check),
    url(r'register/(?P<gift>[\d]+)', RegisterView.as_view()),
)

src/claires/user/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.admin.widgets import AdminFileWidget
from django.forms.widgets import Textarea, TextInput, Select, HiddenInput, FileInput, ClearableFileInput,DateInput
from django.conf import settings
from claires.forms import HTML5RequiredMixin
from .models import *
from claires.utils import phone_clean

class AnketGiftForm(forms.ModelForm):
    date_born = forms.DateField(required=True, label=u"Дата рождения (ДД.ММ.ГГГГ)")
    agree = forms.BooleanField(label=u"С <a href=\"/pages/informaciya/programma-loyalnosti-claires-friends\" target=\"_blank\">правилами клуба</a> ознакомлен(а)", required = True, )
    phone = forms.CharField(label=u"Мобильный телефон",required = True)
    gender = forms.ChoiceField(label=u"Пол", choices=GENDER_IN, widget=forms.RadioSelect())
    #gift = forms.IntegerField(widget=forms.HiddenInput())
    
    class Meta:
        model = Anket
        fields = ("first_name", "last_name", "phone", "email", "date_born", "city", "gender", "is_email_newsleter", "is_sms_newsleter")
        exclude = ['gift']

    def clean_phone(self):
        return phone_clean( self.cleaned_data['phone'] )


class AnketRegisterForm(AnketGiftForm):
    def __init__(self, *args, **kwargs):
        super(AnketRegisterForm, self).__init__(*args, **kwargs)
        self.fields.pop("agree")
        

src/claires/api/views.py
# -*- coding: utf-8 -*-
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.reverse import reverse
from rest_framework.decorators import *
from rest_framework import permissions
from rest_framework_extensions.cache.mixins import CacheResponseMixin
from rest_framework_extensions.etag.mixins import ETAGMixin
from claires.catalog.models import *
from claires.catalog.serializers import *
from claires.vacancies.serializers import *
from claires.vacancies.models import JobsApply
from rest_framework import viewsets
from rest_framework import mixins
from rest_framework import filters
from rest_framework import generics
from rest_framework import pagination
import django_filters





""" PAGINATION"""
class HugeResultsSetPagination(pagination.PageNumberPagination):
    page_size = 1000

class LargeResultsSetPagination(pagination.PageNumberPagination):
    page_size = 100

class StandardResultsSetPagination(pagination.PageNumberPagination):
    page_size = 50

class ProductsResultsSetPagination(pagination.PageNumberPagination):
    page_size = 30

class SmallResultsSetPagination(pagination.PageNumberPagination):
    page_size = 10



"""FILTERS"""
class ProductSearchFilter(filters.FilterSet):
    art = django_filters.MultipleChoiceFilter(choices = [(x.art, x.name) for x in Product.objects.all() ] )

    class Meta:
        model = Product
        fields = ['art']

class ProductFilter(filters.FilterSet):
    min_price = django_filters.NumberFilter(name="product_price__price", lookup_expr='gte')
    max_price = django_filters.NumberFilter(name="product_price__price", lookup_expr='lte')
    group =  django_filters.MethodFilter(action='filter_group')
    categories =  django_filters.MethodFilter(action='filter_category')
    prop = django_filters.ModelMultipleChoiceFilter(queryset = PropertyVariant.objects.filter(is_show=True), conjoined=False)
    art = django_filters.MultipleChoiceFilter(choices = [(x.art, x.name) for x in Product.objects.filter(is_show=True) ] )

    class Meta:
        model = Product
        fields = ['prop', 'art' ,'group', 'categories', 'stores', 'min_price', 'max_price']


    def filter_category(self, queryset, value):
        if value:
            try:
                g = Category.objects.get(site_slug = value)
                """
                return queryset.filter(
                    categories__tree_id = g.tree_id,
                    categories__lft__gte = g.lft,
                    categories__rght__lte = g.rght)
                """
                return g.products.filter(is_show=True, art__isnull=False, images__isnull=False)
            except:
                pass
        return queryset


    def filter_group(self, queryset, value):
        if value:
            try:
                g = Group.objects.get(site_slug = value)
                return queryset.filter(
                    group__tree_id = g.tree_id,
                    group__lft__gte = g.lft,
                    group__rght__lte = g.rght)
            except:
                pass
        return queryset

class ProductBalanceFilter(filters.FilterSet):
    class Meta:
        model = ProductBalance
        fields = ['product', 'store', 'quantity',]



class GroupFilter(filters.FilterSet):
    class Meta:
        model = Group
        fields = ['id', 'site_slug']

class CategFilter(filters.FilterSet):
    class Meta:
        model = Category
        fields = ['id', 'site_slug']



"""VIEWSETS"""
class GroupViewSet(ETAGMixin, CacheResponseMixin, viewsets.ReadOnlyModelViewSet):
    queryset = Group.objects.filter(is_show=True)
    serializer_class = GroupSerializer
    pagination_class = HugeResultsSetPagination
    filter_class = GroupFilter
    filter_backends = (filters.DjangoFilterBackend,)

    def get_view_description(self, html=True):
        return u"Возвращает разделы каталога"



class CategoryViewSet(CacheResponseMixin, viewsets.ReadOnlyModelViewSet):
    queryset = Category.objects.filter(in_menu=True)
    serializer_class = CategorySerializer
    pagination_class = HugeResultsSetPagination
    filter_class = CategFilter
    filter_backends = (filters.DjangoFilterBackend,)

    def get_view_description(self, html=True):
        return u"Возвращает псевдо категории каталога"


class StoresViewSet(CacheResponseMixin, viewsets.ReadOnlyModelViewSet):
    queryset = Stores.objects.filter(is_show=True).order_by("city","date_created")
    serializer_class = StoresSerializer
    pagination_class = SmallResultsSetPagination

    def get_view_description(self, html=True):
        return u"Возвращает магазины"



class ProductViewSet(ETAGMixin, CacheResponseMixin, viewsets.ReadOnlyModelViewSet):
    queryset = Product.objects.filter(is_show=True, images__isnull=False)
    #queryset = Product.objects.filter(is_show=True)
    serializer_class = ProductSerializer
    filter_backends = (filters.OrderingFilter,filters.DjangoFilterBackend,)
    filter_class = ProductFilter
    pagination_class = ProductsResultsSetPagination
    ordering_fields = ('product_price__price', 'name', 'date_created', 'art','barcode')


class ProductSearchViewSet(CacheResponseMixin, viewsets.ReadOnlyModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_class = ProductSearchFilter
    pagination_class = LargeResultsSetPagination
    filter_backends = (filters.OrderingFilter,filters.DjangoFilterBackend,)
    ordering_fields = ('product_price__price', 'name', 'date_created', 'art','barcode')

class ProductStoreViewSet(ETAGMixin, viewsets.ReadOnlyModelViewSet):
    queryset = ProductBalance.objects.filter(store__is_show=True)
    serializer_class = ProductStoreSerializer
    filter_class = ProductBalanceFilter
    pagination_class = SmallResultsSetPagination


class PropViewSet(ETAGMixin, viewsets.ReadOnlyModelViewSet):
    queryset = Property.objects.filter(is_show=True, value_type=2)
    serializer_class = PropSerializer
    pagination_class = LargeResultsSetPagination

class PropVarViewSet(ETAGMixin, viewsets.ReadOnlyModelViewSet):
    queryset = PropertyVariant.objects.filter(is_show=True)
    serializer_class = PropertyVariantSerializer
    pagination_class = LargeResultsSetPagination


class VacanApplyViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = JobsApply.objects.all()
    serializer_class = JobsApplySerializer


    def list(self, request):
        queryset = self.get_queryset()
        serializer = JobsApplySerializer(queryset, many=True)
        return Response(serializer.data)

    def get_queryset(self):
        if self.request.user.is_staff:
            return JobsApply.objects.all()
        else:
            return []

src/claires/banners/views.py
# -*- coding: utf-8 -*-
import json
from django.shortcuts import get_object_or_404
from django.views.generic import View
from django.http import Http404, HttpResponse
from django.conf import settings
from claires.views import ClairesView
from .models import  PageSection, Page



class PageView(ClairesView):
    template_name = "pages/page.html"

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(request, **kwargs)
        response = self.render_to_response(context)
        return response

    def get_context_data(request, *args, **kwargs):
        section  = get_object_or_404(PageSection, slug = kwargs['section'])
        return {
            'page': get_object_or_404(Page, id = kwargs['page_id'], section = section )
        }

src/claires/catalog/views.py
# -*- coding: utf-8 -*-
import json
import datetime
from django.shortcuts import get_object_or_404
from django.views.generic import View
from django.http import Http404, HttpResponse
from django.conf import settings
from claires.views import ClairesView
from claires.catalog.models import *
from claires.catalog.filter import *
from claires.catalog.serializers import *
from django.core import serializers



class ShopsView(ClairesView):
    template_name = "catalog/shops.html"

    def get_context_data(self, request, **kwargs):
        return {
           "API_KEY": settings.GOOGLE_API_KEY,
        }



class CatalogView(ClairesView):
    template_name = "catalog/category.html"

    def get_context_data(self, request, **kwargs):
        return {
            "groups": Group.objects.filter(is_show=True, parent=None)
        }


class CatalogCategoryView(CatalogView):

    def get_context_data(self, request, **kwargs):
        return {
            "group": get_object_or_404(Group, site_slug = kwargs.get("group_slug", None))    
        }



class CatalogCategoryPseudoView(CatalogView):
    def get_context_data(self, request, **kwargs):
        cat = get_object_or_404(Category, site_slug = kwargs.get("category_slug", None))    
        return {
            "category": cat,
            "group": cat,
        }


class CatalogProductView(CatalogView):
    template_name = "catalog/product.html"

    def get_context_data(self, request, **kwargs):
        item = get_object_or_404(Product, site_slug = kwargs.get("product_slug", None))
        return {
            "item": item,
            "siblings": Product.objects.filter(is_show=True, group = item.group,images__isnull=False).exclude(art=item.art).select_related()[:40],
            "groups": Group.objects.filter(is_show=True)
        }

src/claires/import_manager/views.py
# -*- coding: utf-8 -
import os
import logging
from django.http import HttpResponse, Http404
from django.views.decorators.csrf import csrf_exempt
from django.core.files.uploadedfile import SimpleUploadedFile
from .manager import ImportManager
from django.conf import settings
from claires.catalog.models import *

logger = logging.getLogger("import_manager")

IMAGE_EXT = ["jpg", "jpeg", "png"]
#@logged_in_or_basicauth()
@csrf_exempt
def front_view(request):
    return Dispatcher().dispatch(request)

def error(request, error_text):
    logger.error(error_text)
    result = '{}\n{}'.format("error", error_text)
    return HttpResponse(result)


def success(request, success_text=''):
    result = u'{}\n{}'.format("success", success_text)
    return HttpResponse(result)


def check_auth(request):
    session = request.session
    success_text = '{}\n{}'.format(settings.SESSION_COOKIE_NAME, session.session_key)
    logger.info("check_auth ok")
    return success(request, success_text)


def init(request):
    result = 'zip={}\nfile_limit={}'.format('no', str(1024*1024*256*2))
    logger.info("init ok")
    return HttpResponse(result)


def upload_file(request):
    if request.method != 'POST':
        return error(request, 'Wrong HTTP method!')
    try:
        _filename = request.GET['filename']
    except KeyError:
        logger.error("Need a filename param")
        return
    if not os.path.exists(settings.PRODUCT_UPLOAD_DIR):
        try:
            os.makedirs(settings.PRODUCT_UPLOAD_DIR)
        except OSError:
            logger.error("Cant create upload directory!")
            return
    logger.error("Upload file - %s"%_filename)    
    filename = os.path.basename(_filename)
    temp_file = SimpleUploadedFile(filename, request.read())
    filepath = os.path.join(settings.PRODUCT_UPLOAD_DIR, filename)
    try:
        _ext = filename.split(".")[-1]
        if _ext in IMAGE_EXT:
            filepath = os.path.join(settings.PRODUCTS_FOLDER_ROOT, filename)
    except Exception, e:
        logger.error("Image saving error %s"%e)    
    with open(filepath, 'wb') as f:
        for chunk in temp_file.chunks():
            f.write(chunk)
    logger.info("Uploaded file %s: ok"%_filename)
    return success(request)


def import_file(request):
    try:
        filename = request.GET['filename']
        pe = Exchange(filename=filename)
        logger.info("Try import_file - %s"%filename)
    except KeyError:
        message = "Need a filename param"
        logger.error(message)
        pe.update_status("error")
        pe.comment=message
        pe.save()
        return

    file_path = os.path.join(settings.PRODUCT_UPLOAD_DIR, filename)

    if not os.path.exists(file_path):
        message = "File doesnt exists: %s"%file_path
        logger.error(message)
        pe.update_status("error")
        pe.comment = message
        pe.save()
        return

    pe.update_status("progress")
    pe.save()
    import_manager = ImportManager(file_path)
    import_manager.import_all()

    pe.update_status("success")
    pe.save()
    return HttpResponse("success")

def export_query(request):
    pass
    """
    export_manager = ExportManager()
    export_manager.export_all()
    return HttpResponse(export_manager.get_xml(), content_type='text/xml')
    """


def export_success(request):
    pass
    """
    export_manager = ExportManager()
    Exchange.log('export', request.user)
    export_manager.flush()
    return success(request)
    """

class Dispatcher(object):

    def __init__(self):
        self.routes_map = {
            (u'catalog', u'checkauth'): check_auth,
            (u'catalog', u'init'): init,
            (u'catalog', u'file'): upload_file,
            (u'catalog', u'import'): import_file,
            (u'sale', u'file'): upload_file,
            (u'import', u'import'): import_file,
            (u'sale', u'checkauth'): check_auth,
            (u'sale', u'init'): init,
            (u'sale', u'query'): export_query,
            (u'sale', u'success'): export_success,
        }

    def dispatch(self, request):
        view_key = (request.GET.get('type'), request.GET.get('mode'))
        view = self.routes_map.get(view_key)
        if not view:
            raise Http404
        return view(request)

src/claires/locations/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt

src/claires/pages/views.py
# -*- coding: utf-8 -*-
import json
from django.shortcuts import get_object_or_404
from django.views.generic import View
from django.http import Http404, HttpResponse
from django.conf import settings
from claires.views import ClairesView
from .models import  PageSection, Page
from djpjax import PJAXResponseMixin


class PageView(ClairesView):

    template_name = "pages/page.html"
    def get_context_data(self, request, **kwargs):
        context = {}
        section = get_object_or_404(PageSection, slug = kwargs.get("parent",None))
        context["page"] = section
        context["in_menu"] = section.pages
        if kwargs.get("page_slug",None):
            context["page"] = get_object_or_404(Page, section = section, display=True, slug = kwargs.get("page_slug",None))
            context["in_menu"] = context["page"].section.pages
        return context

src/claires/templates/user/fail_register.html
{%extends "base.html"%}
{% load staticfiles%}
{%block title%}Claire's - регистрация{%endblock%}

{%block css_extra%}
 <link href="{% static 'css/page.css'%}?" rel="stylesheet" type="text/css" />
 {%endblock%}


{% block content%}
<div class="container page">
    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb">
                <li><a href="/">Главная</a></li>
                <li class="active">Анкета</li>
            </ol>
            <h1>Регистрация не удалась :(</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-7 content">
        <h2>К сожалению, вы уже зарегистрированы</h2>
        </div>
    </div>
</div>
{%endblock%}

src/claires/templates/user/form.html
{% load bootstrap3 %}
{% if form %}
    {% bootstrap_form_errors form type='fields'%}
    <form action="" method="POST" id="create_user">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "star" %} Отправить!
        </button>
    {% endbuttons %}
    </form>
{% endif %}

src/claires/templates/user/register.html
{%extends "base.html"%}
{% load staticfiles bootstrap3%}
{%block title%}Claire's - регистрация{%endblock%}

{%block css_extra%}
<link href="{% static 'css/page.css'%}?" rel="stylesheet" type="text/css" />
 <link href="{% static 'css/user.css'%}?" rel="stylesheet" type="text/css" />
 {%endblock%}


{%block user_register%}{%endblock%}
{% block content%}

<style>
.custom_closed_pink{
    top: 50px;
    right:0px;    
}
.custom_closed_pink:after {
    content: "×";
    position: absolute;
    top: 50px;
    right:0px;
    width: 40px;
    height: 40px;
    font: 26px/30px Arial,Helvetica,sans-serif;
    color: #000;
    font-weight: 300;
    text-align: center;
    border-radius: 0;
    border-width: 0;
    background: #F5D3E5;
    transition: background .2s;
    box-sizing: border-box;
    z-index: 2;
}
</style>

<div class="modal fade success_modal" tabindex="-1" role="dialog" aria-labelledby="success_modal">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Регистрация успешно завершена!</h4>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer">
                <a class="btn btn-default" href="/">На главную</a>
                <a class="btn btn-claires" href="/shops/">Список магазинов</a>
      </div>
        </div>
    </div>
</div>



<div class="container page">
    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb">
                <li><a href="/">Главная</a></li>
                <li class="active">Анкета</li>
            </ol>
            <h1>{%if gift%}{{gift.name}}{%else%}Регистрация{%endif%}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 content">
            {%if gift.content%}
                <div class="form__content">{{gift.content|safe}}</div>
            {%endif%}
            <form action="" method="POST" id="create_user">
            {% csrf_token %}
            {% bootstrap_form form exclude="gift, agree, is_email_newsleter, is_sms_newsleter" placeholder=''%}

            <div class="form__custom_checks">
                {% bootstrap_field form.is_email_newsleter %}
                {% bootstrap_field form.is_sms_newsleter %}
                {% bootstrap_field form.agree %}
            </div>
            {%if gift.post_content%}
                <div class="form__content">{{gift.post_content|safe}}</div>
            {%endif%}

            {% buttons %}
                <button type="submit" class="btn btn-primary btn-lg anket_submit">
                    {% bootstrap_icon "star" %} Отправить!
                </button>
            {% endbuttons %}
            <input type="hidden" name="register_id" value="{{gift.id}}">
            </form>
        </div>
    </div>
    {%if gift.image%}
    <div class="row">
        <div class="col-md-12">
            <img src="{{gift.image.url}}" class="img-responsive">
        </div>
    </div>
    {%endif%}
</div>
{%endblock%}



{%block extra%}
<script src="{% static 'js/bootstrapValidator.js'%}" type="text/javascript"></script>
<script src="http://www.valtera.ru/static/2014/js/jquery.maskedinput.min.js"></script>
<script type="text/javascript">

var phoneValidate = function(form_name){
    $('[id*="phone"]').bind("change blur click", function(a){
        $(form_name).bootstrapValidator("revalidateField",$(this))
    })
    .mask('7-999-999-99-99', {placeholder: "_"});
}


$(document).ready(function() {

    $(".fancybox").fancybox();

    var form_name  = "#create_user";

    $(form_name).bootstrapValidator({
        container: 'popover',
        excluded: [':disabled', ':hidden', ':not(:visible)'],
        feedbackIcons: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            phone: {
                validators: {
                    notEmpty: {
                        message: 'Пожалуйста, укажи свой номер телефона для завершения регистрации!'
                    },
                    remote: {
                        url: '/user/register/phone_check/',
                        type:'GET',
                        name:'tel',
                        delay: 1000,
                        message: 'Этот номер уже зарегистрирован',
                        failCallback: function () { 
                            alert("Этот номер уже зарегистрирован");
                        },
                        doneCallback: function () { 
                            message: 'Круто, ты-то нам и нужен!'
                        }
                    }
                }
            },
            last_name: {
                validators: {
                    notEmpty: {
                        message: 'Пожалуйста, заполни это поле для завершения регистрации!'
                    }
                }
            },
            first_name: {
                validators: {
                    notEmpty: {
                        message: 'Пожалуйста, заполни это поле для завершения регистрации!'
                    }
                }
            },
            gender: {
                validators: {
                    notEmpty: {
                        message: 'Пожалуйста, укажи свой пол для завершения регистрации!'
                    }
                }
            },
            email: {
                validators: {
                    notEmpty: {
                        message: 'Пожалуйста, заполни это поле для завершения регистрации!'
                    },
                    emailAddress: {
                        message: 'Введите корректно свой Email'
                    }
                }
            },
            date_born: {
                validators: {
                    notEmpty: {
                        message: 'Пожалуйста, заполни это поле для завершения регистрации!'
                    },
                    date: {
                        message: 'Укажи дату в формате дд.мм.гггг',
                        format: 'DD.MM.YYYY',
                        separator:'.',
                        range:"01.01.1900-01.01.2000"
                    }
                }
            },
            city: {
                validators: {
                    notEmpty: {
                        message: 'Пожалуйста, заполни это поле для завершения регистрации!'
                    },
                    stringLength: {
                        min:2,
                        message: 'Длинна строки слишком короткая'
                    }
                }
            },
            agree: {
                validators: {
                    notEmpty: {
                        message: 'Пожалуйста, заполни это поле для завершения регистрации!'
                    },
                    choice: {
                        min: 1,
                        max: 2,
                        message: 'Для завершения регистрации необходимо согласиться с правилами клуба!'
                    }
                }
            },
        }
    })
    .on('error.form.bv', function(e, data) {
        console.log(data);
    })
    .on('success.form.bv', function(e) {
        if($("#id_agree").is(':not(:checked)')){
            $("#id_agree").tooltip('show');
            return false;
        }

        e.preventDefault();
        $(".anket_submit").text("Отправляем анкету...")
        var $form = $(e.target);
            $.post($form.attr('action'), $form.serialize(), function(result) {
                $(".success_modal .modal-body").html(result.message);
                $('.success_modal').modal({
                    keyboard: false,
                    show:false
                }).modal("show");
                if(result.done){
                    $form.find("input").prop("disabled", true);
                    $(".anket_submit").text("Анкета отправлена")
                    $("submit[type=submit]").hide();
                    $("h1").text("Регистрация завершена");
                }else{
                    $(".success_modal .modal-title").text("Регистрация не завершена");
                    $(".anket_submit").text("Отправить!")
                }
            });
    });
   phoneValidate(form_name);

    $(".pinked_fancybox").fancybox({
        slideShow  : false,
        fullScreen : false,
        thumbs     : false,
        closeBtn   :false
    });
});
</script>
{%endblock%}

src/claires/templates/user/success_register.html
{%extends "base.html"%}
{% load staticfiles%}
{%block title%}Claire's - регистрация{%endblock%}

{%block css_extra%}
 <link href="{% static 'css/page.css'%}?" rel="stylesheet" type="text/css" />
 {%endblock%}


{% block content%}
<div class="container page">
    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb">
                <li><a href="/">Главная</a></li>
                <li class="active">Анкета</li>
            </ol>
            <h1>Регистрация завершена!</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-7 content">
            <p>{{gift.message_success}}</p>
        </div>
    </div>
    {%if gift.image%}
    <div class="row">
        <div class="col-md-12">
            <img src="{{gift.image.url}}" class="img-responsive">
        </div>
    </div>
    {%endif%}
</div>
{%endblock%}