src/claires/api/urls.py
from django.conf.urls import patterns, url, include
from claires.views import ClairesView
from .views import *
from rest_framework import routers
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework_cache.registry import cache_registry
cache_registry.autodiscover()

router = routers.DefaultRouter()
router.register(r'jobsapply', VacanApplyViewSet)
router.register(r'groups', GroupViewSet)
router.register(r'category', CategoryViewSet)
router.register(r'stores', StoresViewSet)
router.register(r'products', ProductViewSet)
router.register(r'products_search', ProductSearchViewSet)
router.register(r'product_stores', ProductStoreViewSet)
router.register(r'props', PropViewSet)
router.register(r'prop_vars', PropVarViewSet)



urlpatterns = [
    url(r'^', include(router.urls, namespace='api'))
]

#urlpatterns = format_suffix_patterns(urlpatterns)

src/claires/pages/urls.py
from django.conf.urls import patterns, url, include
from .views import PageView

urlpatterns = patterns('',
    url(r'(?P<parent>[\w\d\-]+)/(?P<page_slug>[\w\d\-]+)', PageView.as_view()),
    url(r'(?P<parent>[\w\d\-]+)/$', PageView.as_view()),
)

src/claires/partials/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.static import static
from filebrowser.sites import site
try:
    from django.conf.urls import patterns, url, include
except ImportError:
    from django.conf.urls.defaults import *
from django.conf import  settings
from django.contrib import admin
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.views.generic import RedirectView, TemplateView,ListView
from django.http import Http404, HttpResponse
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles import views
from .views import *

urlpatterns = patterns('',
  url(r'^(?P<tpl>[\w\d\-\.]+)', PartialGroupView.as_view(template_name='partials/partial-template1.html'), name='partial_template1'),
)

src/claires/search/urls.py
from django.conf.urls import patterns, url, include
from .views import SearchView

urlpatterns = patterns('',
    url(r'$', SearchView.as_view()),
)

src/claires/user/urls.py
from django.conf.urls import patterns, url, include
from .views import *

urlpatterns = patterns('',
    url(r'register$', RegisterView.as_view(), {"gift":None} ),
    url(r'register/phone_check/$', phone_check),
    url(r'register/(?P<gift>[\d]+)', RegisterView.as_view()),
)

src/claires/import_manager/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings


src/claires/vacancies/models.py
# -*- coding: utf-8 -*-
import datetime
from django.db import models

JOBS_IN = (
    (1,u'Работа в магазинах'),
    (2,u'Работа в офисе'),
)


MARTIAL_IN = (
    (1,u'Не замужем/Не женат'),
    (2,u'Замужем/Женат'),
    (3,u'Разведен(а)'),
)

EDU_IN = (
    (1,u'Не имею'),
    (2,u'Среднее'),
    (3,u'Среднее специальное'),
    (4,u'Неоконченное высшее'),
    (4,u'Высшее'),
)

PC_EDU_IN = (
    (1,u'Профессионально (системный администратор, наладка оборудования и пр.)'),
    (2,u'Продвинутый пользователь (отличное знание пакета MS Office, 1C и т.д.)'),
    (3,u'Пользователь (базовые знания основных программ Windows и пакета MS Office)'),
    (4,u'Не работаю на ПК'),
)
"""
class Vacancies(models.Model):
    jobs_in = models.PositiveIntegerField(u'Работа в', default=1, choices=JOBS_IN)
    name = models.CharField(u'Краткое название вакансии', null=True, blank=True, max_length=60)
    short_description = models.CharField(u'Заголовок вакансии', null=True, blank=True, max_length=500)
    full_description = models.TextField(u'Полное описание вакансии', null=True, blank=True)
    resume = models.BooleanField(u'Послать резюме', default=False)
    ankett = models.BooleanField(u'Заполнить анкету', default=False)
    hide = models.BooleanField(u'В архиве', default=False)
    

    def __unicode__(self): 
        return self.full_name

    class Meta: 
        verbose_name,verbose_name_plural = u'Вакансия',u'Вакансии'

    def get_absolute_url(self):
        return "/vacancies/%s"%self.id

    def get_new_absolute_url(self):
        return "/vacancies/%s"%self.id
"""

class JobsApply(models.Model):
    vacancy = models.CharField(u'Вакансия', null=True, blank=True, max_length=200, help_text=u'Укажите вакансию')
    FIO = models.CharField(u'Фамилия Имя', null=True, blank=True, max_length=200)
    email = models.EmailField(u'E-mail', null=True, blank=True)
    phone = models.CharField(u'Мобильный телефон', null=True, blank=True, max_length=21)
    date_of_birth = models.DateField(u"Дата рождения")
    address_of_registration = models.CharField(u'Адрес постоянной регистрации', null=True, blank=True, max_length=300)
    address_of_living = models.CharField(u'Адрес проживания', null=True, blank=True, max_length=300)
    cash_register = models.CharField(u'Опыт работы с кассовым аппаратом (каким)', null=True, blank=True, max_length=300)
    marital_status = models.PositiveIntegerField(u'Семейное положение', default=1, choices=MARTIAL_IN)
    computer_knowledge = models.PositiveIntegerField(u'Степень владения ПК', default=1, choices=PC_EDU_IN)
    education = models.PositiveIntegerField(u'Образование', default=2, choices=EDU_IN)
    experience = models.TextField(u'Опыт работы', null=True, blank=True)
    cv = models.FileField(u'Резюме', upload_to='jobs/', null=True, blank=True, help_text=u"Если у вас есть готовое резюме, загрузите его здесь")
    date_added = models.DateTimeField(u'Дата создания', default=datetime.datetime.now)
    ip = models.GenericIPAddressField(protocol="IPv4", default="127.0.0.1")


    def __unicode__(self): 
        return u"%s - %s"%(self.FIO, self.vacancy)

    def get_admin_full_url(self):
        return u"http://www.claires.ru/admin/vacancies/jobsapply/%s/change/"%self.id

    class Meta: verbose_name,verbose_name_plural = u'Анкета',u'Анкеты'

src/claires/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.admin.widgets import AdminFileWidget
from django.forms.widgets import Textarea, TextInput, Select, HiddenInput, FileInput, ClearableFileInput,DateInput


class HTML5RequiredMixin(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(HTML5RequiredMixin, self).__init__(*args, **kwargs)
        for field in self.fields:
            if type(self.fields[field].widget) not in (AdminFileWidget, HiddenInput, FileInput, ClearableFileInput):
                self.fields[field].widget.attrs['required'] = 'required'
                if self.fields[field].label:
                    self.fields[field].label += ' *'

src/claires/api/views.py
# -*- coding: utf-8 -*-
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.reverse import reverse
from rest_framework.decorators import *
from rest_framework import permissions
from rest_framework_extensions.cache.mixins import CacheResponseMixin
from rest_framework_extensions.etag.mixins import ETAGMixin
from claires.catalog.models import *
from claires.catalog.serializers import *
from claires.vacancies.serializers import *
from claires.vacancies.models import JobsApply
from rest_framework import viewsets
from rest_framework import mixins
from rest_framework import filters
from rest_framework import generics
from rest_framework import pagination
import django_filters





""" PAGINATION"""
class HugeResultsSetPagination(pagination.PageNumberPagination):
    page_size = 1000

class LargeResultsSetPagination(pagination.PageNumberPagination):
    page_size = 100

class StandardResultsSetPagination(pagination.PageNumberPagination):
    page_size = 50

class ProductsResultsSetPagination(pagination.PageNumberPagination):
    page_size = 30

class SmallResultsSetPagination(pagination.PageNumberPagination):
    page_size = 10



"""FILTERS"""
class ProductSearchFilter(filters.FilterSet):
    art = django_filters.MultipleChoiceFilter(choices = [(x.art, x.name) for x in Product.objects.all() ] )

    class Meta:
        model = Product
        fields = ['art']

class ProductFilter(filters.FilterSet):
    min_price = django_filters.NumberFilter(name="product_price__price", lookup_expr='gte')
    max_price = django_filters.NumberFilter(name="product_price__price", lookup_expr='lte')
    group =  django_filters.MethodFilter(action='filter_group')
    categories =  django_filters.MethodFilter(action='filter_category')
    prop = django_filters.ModelMultipleChoiceFilter(queryset = PropertyVariant.objects.filter(is_show=True), conjoined=False)
    art = django_filters.MultipleChoiceFilter(choices = [(x.art, x.name) for x in Product.objects.filter(is_show=True) ] )

    class Meta:
        model = Product
        fields = ['prop', 'art' ,'group', 'categories', 'stores', 'min_price', 'max_price']


    def filter_category(self, queryset, value):
        if value:
            try:
                g = Category.objects.get(site_slug = value)
                """
                return queryset.filter(
                    categories__tree_id = g.tree_id,
                    categories__lft__gte = g.lft,
                    categories__rght__lte = g.rght)
                """
                return g.products.filter(is_show=True, art__isnull=False, images__isnull=False)
            except:
                pass
        return queryset


    def filter_group(self, queryset, value):
        if value:
            try:
                g = Group.objects.get(site_slug = value)
                return queryset.filter(
                    group__tree_id = g.tree_id,
                    group__lft__gte = g.lft,
                    group__rght__lte = g.rght)
            except:
                pass
        return queryset

class ProductBalanceFilter(filters.FilterSet):
    class Meta:
        model = ProductBalance
        fields = ['product', 'store', 'quantity',]



class GroupFilter(filters.FilterSet):
    class Meta:
        model = Group
        fields = ['id', 'site_slug']

class CategFilter(filters.FilterSet):
    class Meta:
        model = Category
        fields = ['id', 'site_slug']



"""VIEWSETS"""
class GroupViewSet(ETAGMixin, CacheResponseMixin, viewsets.ReadOnlyModelViewSet):
    queryset = Group.objects.filter(is_show=True)
    serializer_class = GroupSerializer
    pagination_class = HugeResultsSetPagination
    filter_class = GroupFilter
    filter_backends = (filters.DjangoFilterBackend,)

    def get_view_description(self, html=True):
        return u"Возвращает разделы каталога"



class CategoryViewSet(CacheResponseMixin, viewsets.ReadOnlyModelViewSet):
    queryset = Category.objects.filter(in_menu=True)
    serializer_class = CategorySerializer
    pagination_class = HugeResultsSetPagination
    filter_class = CategFilter
    filter_backends = (filters.DjangoFilterBackend,)

    def get_view_description(self, html=True):
        return u"Возвращает псевдо категории каталога"


class StoresViewSet(CacheResponseMixin, viewsets.ReadOnlyModelViewSet):
    queryset = Stores.objects.filter(is_show=True).order_by("city","date_created")
    serializer_class = StoresSerializer
    pagination_class = SmallResultsSetPagination

    def get_view_description(self, html=True):
        return u"Возвращает магазины"



class ProductViewSet(ETAGMixin, CacheResponseMixin, viewsets.ReadOnlyModelViewSet):
    queryset = Product.objects.filter(is_show=True, images__isnull=False)
    #queryset = Product.objects.filter(is_show=True)
    serializer_class = ProductSerializer
    filter_backends = (filters.OrderingFilter,filters.DjangoFilterBackend,)
    filter_class = ProductFilter
    pagination_class = ProductsResultsSetPagination
    ordering_fields = ('product_price__price', 'name', 'date_created', 'art','barcode')


class ProductSearchViewSet(CacheResponseMixin, viewsets.ReadOnlyModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_class = ProductSearchFilter
    pagination_class = LargeResultsSetPagination
    filter_backends = (filters.OrderingFilter,filters.DjangoFilterBackend,)
    ordering_fields = ('product_price__price', 'name', 'date_created', 'art','barcode')

class ProductStoreViewSet(ETAGMixin, viewsets.ReadOnlyModelViewSet):
    queryset = ProductBalance.objects.filter(store__is_show=True)
    serializer_class = ProductStoreSerializer
    filter_class = ProductBalanceFilter
    pagination_class = SmallResultsSetPagination


class PropViewSet(ETAGMixin, viewsets.ReadOnlyModelViewSet):
    queryset = Property.objects.filter(is_show=True, value_type=2)
    serializer_class = PropSerializer
    pagination_class = LargeResultsSetPagination

class PropVarViewSet(ETAGMixin, viewsets.ReadOnlyModelViewSet):
    queryset = PropertyVariant.objects.filter(is_show=True)
    serializer_class = PropertyVariantSerializer
    pagination_class = LargeResultsSetPagination


class VacanApplyViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = JobsApply.objects.all()
    serializer_class = JobsApplySerializer


    def list(self, request):
        queryset = self.get_queryset()
        serializer = JobsApplySerializer(queryset, many=True)
        return Response(serializer.data)

    def get_queryset(self):
        if self.request.user.is_staff:
            return JobsApply.objects.all()
        else:
            return []

src/claires/banners/views.py
# -*- coding: utf-8 -*-
import json
from django.shortcuts import get_object_or_404
from django.views.generic import View
from django.http import Http404, HttpResponse
from django.conf import settings
from claires.views import ClairesView
from .models import  PageSection, Page



class PageView(ClairesView):
    template_name = "pages/page.html"

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(request, **kwargs)
        response = self.render_to_response(context)
        return response

    def get_context_data(request, *args, **kwargs):
        section  = get_object_or_404(PageSection, slug = kwargs['section'])
        return {
            'page': get_object_or_404(Page, id = kwargs['page_id'], section = section )
        }

src/claires/catalog/views.py
# -*- coding: utf-8 -*-
import json
import datetime
from django.shortcuts import get_object_or_404
from django.views.generic import View
from django.http import Http404, HttpResponse
from django.conf import settings
from claires.views import ClairesView
from claires.catalog.models import *
from claires.catalog.filter import *
from claires.catalog.serializers import *
from django.core import serializers



class ShopsView(ClairesView):
    template_name = "catalog/shops.html"

    def get_context_data(self, request, **kwargs):
        return {
           "API_KEY": settings.GOOGLE_API_KEY,
        }



class CatalogView(ClairesView):
    template_name = "catalog/category.html"

    def get_context_data(self, request, **kwargs):
        return {
            "groups": Group.objects.filter(is_show=True, parent=None)
        }


class CatalogCategoryView(CatalogView):

    def get_context_data(self, request, **kwargs):
        return {
            "group": get_object_or_404(Group, site_slug = kwargs.get("group_slug", None))    
        }



class CatalogCategoryPseudoView(CatalogView):
    def get_context_data(self, request, **kwargs):
        cat = get_object_or_404(Category, site_slug = kwargs.get("category_slug", None))    
        return {
            "category": cat,
            "group": cat,
        }


class CatalogProductView(CatalogView):
    template_name = "catalog/product.html"

    def get_context_data(self, request, **kwargs):
        item = get_object_or_404(Product, site_slug = kwargs.get("product_slug", None))
        return {
            "item": item,
            "siblings": Product.objects.filter(is_show=True, group = item.group,images__isnull=False).exclude(art=item.art).select_related()[:40],
            "groups": Group.objects.filter(is_show=True)
        }

src/claires/locations/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt

src/claires/pages/views.py
# -*- coding: utf-8 -*-
import json
from django.shortcuts import get_object_or_404
from django.views.generic import View
from django.http import Http404, HttpResponse
from django.conf import settings
from claires.views import ClairesView
from .models import  PageSection, Page
from djpjax import PJAXResponseMixin


class PageView(ClairesView):

    template_name = "pages/page.html"
    def get_context_data(self, request, **kwargs):
        context = {}
        section = get_object_or_404(PageSection, slug = kwargs.get("parent",None))
        context["page"] = section
        context["in_menu"] = section.pages
        if kwargs.get("page_slug",None):
            context["page"] = get_object_or_404(Page, section = section, display=True, slug = kwargs.get("page_slug",None))
            context["in_menu"] = context["page"].section.pages
        return context

src/claires/partials/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404
from django.views.generic import View
from django.http import Http404, HttpResponse
from django.conf import settings
from django.views.generic import TemplateView, View

class PartialGroupView(TemplateView):
    def get_context_data(self, **kwargs):
        if kwargs.get("tpl", None):
            self.template_name = "partials/%s"%kwargs.get("tpl")
        context = super(PartialGroupView, self).get_context_data(**kwargs)
        return context

src/claires/templates/vacancies/ankett.html
{% extends 'base.html' %}
{% load thumbnail staticfiles catalog compress%}


{%block titleblock%}Карьера - Заполнить анкету{%endblock%}

{%block metablock%}
<meta name="description" content="Заполните анкету">
{%endblock%}

{% block css_extra %}
 <link href="{% static 'css/page.css'%}?" rel="stylesheet" type="text/css" />
 <link href="{% static 'css/job.css'%}?" rel="stylesheet" type="text/css" />
{% endblock %}



{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ol class="breadcrumb">
                    <li><a href="/">Главная</a></li>
                    <li class="active"><a href="/job/">Вакансии</a></li>
                </ol>
                <h1>Работа у нас</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-md-7">
                <form enctype="multipart/form-data"  class="ankett_form" action="/job/form" method="post">
                    <h2>Анкета</h2>
                    {% csrf_token %}
                    <ul class="ankett_form__fileds">
                    {{ form }}
                    </ul>
                    <button type="submit" class="btn btn-info">Отправить анкету <i class="fa fa-angle-right"></i></button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

src/claires/templates/vacancies/ankett_done.html
{% extends 'base.html' %}
{% load thumbnail staticfiles catalog compress%}


{%block titleblock%}Карьера - Анкета отправлена{%endblock%}

{%block metablock%}
<meta name="description" content="Анкета соискателя отправлена">
{%endblock%}

{% block css_extra %}
 <link href="{% static 'css/page.css'%}?" rel="stylesheet" type="text/css" />
 <link href="{% static 'css/job.css'%}?" rel="stylesheet" type="text/css" />
{% endblock %}



{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ol class="breadcrumb">
                    <li><a href="/">Главная</a></li>
                    <li class="active"><a href="/job/">Вакансии</a></li>
                </ol>
                <h1>Работа у нас</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-md-7">
               <p>Анкета успешно отправлена. В ближайшее время наши специалисты ее рассмотрят. |<br />Спасибо за проявленный интерес!</p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

src/claires/templates/vacancies/vacancies.html
{%extends "base.html"%}

{% load thumbnail staticfiles catalog compress%}

{%block title%}Claire's - вакансии{%endblock%}

{%block meta%}
    <meta name="description" content="Работайте в Claire's!">
    <meta name="keywords" content="Вакансии claires">
    <meta property="og:image" content="{%thumbnail item.image.image  "200x200" as image_a%}http://www.claires.ru/media/{{image_a}}{%endthumbnail%}" />
    <meta property="og:title" content="{%if item.get_seo.title%}{{item.get_seo.title}}{%else%}{{item.site_name}}{%endif%}" />
    <meta property="og:description" content="{%if item.get_seo.description %}{{item.get_seo.description}}{%else%}{{item.site_name}} в магазинах Claires{%endif%}"/>
    <meta property="og:url" content="http://www.claires.ru{{item.get_absolute_url}}" />
    <meta property="og:site_name" content="Claire's - один из ведущих мировых брендов модных украшений и аксессуаров по доступным ценам." />
{%endblock%}

{%block css_extra%}
 <link href="{% static 'css/page.css'%}?v=432" rel="stylesheet" type="text/css" />
 <link href="{% static 'css/job.css'%}?v=342" rel="stylesheet" type="text/css" />
{%endblock%}

{%block extra%}{%endblock%}



{%block content%}
<script id="vacancy-grid-tpl" type="text/ng-template">
    <div class="col-md-12">
        <h3>{$VacDetailCtrl.vac_detail.data.name $}</h3>
        <ul class="job__annotate">
            <li>Опыт: {$ VacDetailCtrl.vac_detail.data.experience.name $}</li>
            <li>{$ VacDetailCtrl.vac_detail.data.employment.name $}</li>
        </ul>
        <p class="description" ng-bind-html="VacDetailCtrl.vac_detail.data.description"></p>
        <div class="form-group">
            <a class="btn btn-default" href="{$ VacDetailCtrl.vac_detail.data.apply_alternate_url$}" style="background: #f00;color:#fff;">Откликнуться на HH.RU</a>
            <a class="btn btn-default" href="{$ VacDetailCtrl.vac_detail.data.alternate_url$}"  style="background: #f00;color:#fff;">Смотреть на HH.RU</a>
            <a class="btn btn-default" href="/job/form?vac={$VacDetailCtrl.vac_detail.data.name $}" style="background: #543e97;color:#fff;margin-left:10px;font-weight: bold;">Заполнить нашу анкету</a>
        </div>
    </div>
</script>


<script id="vacancy-grid-tpl-default" type="text/ng-template">
    <img src="/media/uploads/cle2.jpg"/></p>
    <p>Наша дружная команда крупнейшего международного бренда <strong>Claire&rsquo;s</strong> всегда рада амбициозным и целеустремленным людям.<br /> Мы ценим желание профессионально расти, учиться и строить карьеру в мире моды.&nbsp;</p>
    <p>Работа в Claire&rsquo;s &ndash; это работа в команде молодых и опытных специалистов.</p>
    <p>Работа в Claire&rsquo;s &ndash; это большие возможности для роста и развития в современной компании.</p>
    <p>Работа в Claire&rsquo;s &ndash; это дружная команда амбициозных людей.</p>
    <p>Работа в Claire&rsquo;s &ndash; это возможность бесплатного обучения и своевременная заработная плата.</p>
    <p></p>
    <p><strong>Claire&rsquo;s</strong> &ndash; это мир современной моды и последних трендов.</p>
    <p></p>
    <p></p>
    <p>У нас:
    <ul>
        <li>Красивый и просторный офис</li>
        <li>Современное оснащение рабочих мест</li>
        <li>Отлаженные бизнес-процессы</li>
        <li>Отличный дружный коллектив!</li>
    </ul>
    </p>
    <p>Быть частью Claire&rsquo;s &ndash; значит быть частью мира моды.</p>
</script>



<div class="content page vacancies" ng-controller="VacCtrl as vac" ng-init="vac.getAllVacancies()">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ol class="breadcrumb">
                    <li><a href="/">Главная</a></li>
                    <li class="active"><a href="/job/">Вакансии</a></li>
                </ol>
                <h1>Работа у нас</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <ul class="list-group job__list">
                    <li class="list-group-item" ng-repeat="v in vac.vac_list">
                        <a href="/job/#!/{$v.id$}" >{$v.name $}</a>
                    </li>
                </ul>
            </div>
            <div class="col-md-8" ng-cloak ng-view></div>
        </div>
    </div>
</div>
{%endblock%}

src/claires/templates/vacancies/vacancy_page.html
{% extends 'base.html' %}
{%block titleblock%}Карьера - Ювелирный интернет-магазин Valtera| {{vacancy.short_name}}{%endblock%}

{%block metablock%}
<meta name="description" content="Карьера.Работайте на нас! Вакансии компании ">
{%endblock%}


{% block banner %}
 <style>
.innerPageCarousel {height: 150px;width:100%;background: url(/static/2014/img/vacancies/_1_innerPage.jpg) center; min-height: 150px;}
 </style>
<div  class="top-bordered innerPageCarousel hidden-xs"></div>
{%endblock%}


{%block content%}
<script type="text/javascript">
var google_tag_params = {
    ecomm_prodid:   '0',
    ecomm_pagetype: 'other',
    ecomm_pvalue:   '0'
};
window.APRT_DATA = {
    pageType: 0
} 
</script>
<link href="{{ STATIC_URL }}2014/css/vacancies.css" rel="stylesheet" type="text/css" />
<section class="vacancies">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <ol class="breadcrumb">
                        <li><a href="/" title="Вернуться на главную страницу">Главная</a></li>
                        <li><a href="/vacancies/">Карьера</a></li>
                        <li class="active">{{vacancy.short_name}}</li>
                    </ol>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-xs-12">
                <table class="table table-striped table-hover">
                {% for k in vacancies_list %}
                    <tr{% ifequal k.id id %} class="active"{%endifequal%}><td><a href="{{ k.get_absolute_url }}">{{ k.short_name }}</a></td></tr>
                {% endfor %}
                </table>
            </div>
             <div class="col-md-8 col-xs-12">
                <h1>{{ vacancy.short_description }}</h1>
                    <span class="vacancie_w_type">{{vacancy.get_jobs_in_display}}</span>
                    {{ vacancy.full_description|safe }}
                {%if vacancy.resume %}
                    <div align="right"><a id="id_resume" class="btn btn-default btn_purple" title="Допустимые расширения файла:rtf,pdf,doc,docx,txt,csv"><i class="fa fa-upload"></i> Отправить резюме</a></div>
                {% endif%}


            </div>
        </div>
    </div>
</section>

<script type="text/javascript" src="http://bp.yahooapis.com/2.4.21/browserplus-min.js"></script>
<script type="text/javascript" src="/static/new_ver/js/plupload.full.js"></script>

<script type="text/javascript">
$(function() {

    var uploader = new plupload.Uploader({
        runtimes : 'gears,html5,flash,silverlight,browserplus',
        file_data_name:'qqfile',
        browse_button : 'id_resume',
        max_file_size : '10mb',
        url : '/vacancies/{{vacancy.jobs_in}}/vacancy/{{ vacancy.id }}/upload_cv/',
        flash_swf_url : '/static/new_ver/js/plupload.flash.swf',
        silverlight_xap_url : '/static/new_ver/js/plupload.silverlight.xap',
        filters : [
            {title : "Text files", extensions : "rtf,pdf,doc,docx,txt,csv,odt"}
        ]
    });

    uploader.init();

    uploader.bind('FilesAdded', function(up, files) {

        $.fancybox({
            'href':"/fancybox/captcha",
            'type':'ajax',
            'loop': false,
            'easingIn'      : 'easeInOutQuart',
            'easingOut': 'easeInOutElastic',
            'scrolling': 'no',
            'beforeClose': function(){

            }
        });
    });
    window.CAPTCHACALL = function() { 
        uploader.start();
    }
    uploader.bind('Error', function(up, err) {
        $.fancybox({
            'content':"<h4>Ошибка!</h4><p>" +err.message +"</p>",
            'loop': false,
            'easingIn'      : 'easeInOutQuart',
            'easingOut': 'easeInOutElastic',
            'scrolling': 'no'
        });
    });

    uploader.bind('FileUploaded', function(up, file) {
        _gaq.push(['_trackPageview', '/resume/success']);
        $.fancybox({
        'content':"<h4>Ваше резюме отправлено!</h4><p>Наши специалисты рассмотрят его в ближайшее время</p>",
        'loop': false,
        'easingIn'      : 'easeInOutQuart',
        'easingOut': 'easeInOutElastic',
        'scrolling': 'no'
        });

    });
});
</script>
          
{%endblock%}